import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import ScrollIntoView from "@/components/scroll-into-view";

const nunito = Nunito({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ToDo - task manager",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunito.className} antialiased`}>
        <ScrollIntoView />
        {children}
      </body>
    </html>
  );
}
